### ISSUE TITLE
Bug when run yarn appium:android

### ISSUE THREAD

**Issue by nguyencaochien** [patw0929/RNAlbumsPractice#2]
This issue when run command : yarn appium:android.

$ DEVICE_TYPE=Android DEVICE_NAME='ASUS' mocha `find src test -name '*.android.t
est.js'`
'DEVICE_TYPE' is not recognized as an internal or external command,

Pleale help to fix!

Thanks.

**Comment by patw0929** [comment]
`DEVICE_TYPE` & `DEVICE_NAME` are environment variable here, it should not cause errors.
I assume you are using Windows, please refer to this:
https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman

**Comment by SystemBlad** [comment]
HI, for windows try this way:
"appium:android": "SET DEVICE_TYPE=Android  && SET DEVICE_NAME='ASUS' && mocha `find src test -name '*.android.test.js'`"
